before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: MhiUvpqg30iJDAowTNIPWNaJYyo3rf4NBVP9yWemXU3TEKIMQYtRnS2MxSChy/TcqL3lBVIneRJJ8Or6R1m6V2HicESuLzNVJBPjuu5oLvLig5YqhiSDGvlpd+sZ5ny48rodofp/zASc953vusQYObKMwPq9AqLcUq/S6qw4WW9Wnd39Ozxsm9M5Kr11a2a1FVVV/YeBFKRU4vriTYB/kWyiLfNg3mCq4FtKsVycOxW+wjjJIZZJptvZgTrCr1EpD11bwugn83DSc3pbnJKAJAjhZWIaELHIQkzWuX+AZ6yP+2I+ESu52qxpE1C4dzUr0uu+TNbGszl7D3FoDlWdP88/n6TbaEWqq2Pg9pur6x9RWUO/Lghg1DV6kAEV4SfgEWply/5AnR2hv9f2jCrhgaKLFM1oGqA5ZQkecunPtsUR9bMM/lXuootDKhjPQehFw0YmBefdlRiiA4P/FJLb6u3ewg2kQE9kzxSsolJ96XKU6X8RqRkTnG/7ldT12nP5Eel31Kc4Is+EfdQhTfn2cm+wCri6hsHBKREUpyEsXVp2wAXVDWGTfQ9MRj21GMz/i79w8wKe/19N6qWU4EZMNMFu3rtSWAXAKeJgVcT3fesGSjWkoEgIszIf0o33yEPaGYrFj4gFnzCdzysqM3UitPPai+9H83haDODZiChn3vQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
